version: '3.1'
services:
  database:
    image: mysql:5.7
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql-mode=STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION
      --explicit_defaults_for_timestamp=ON
      --character-set-server=utf8
      --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
